### ISSUE TITLE
Does this approach allow consuming multicast traffic inside the cluster generated from outside?

### ISSUE THREAD

**Issue by arrcher** [spectriclabs/k8s-mcast-example#1]
Hello, the question is in the title. 
if I need to have a multicast traffic consumer inside the cluster but my traffic producer has to be outside the cluster but on the same physical network. 
Will this approach work?

Thanks.

**Comment by bagoulla** [comment]
@arrcher Yes that is exactly what this approach allows. You cannot achieve the same data rates as you would if you were on the true host network as this is a limitation of the macvlan driver. You can get a bit higher datarates using ipvlan instead of macvlan. I demonstrated macvlan because in the CentOS 7 image used (3.10 kernel) only macvlan is available.

If you need high datarate multicast you would need to use host networking or an SR-IOV CNI based approach which isn't supported by all hardware NICs.

**Comment by arrcher** [comment]
Thanks @bagoulla, this works.
